name: 'Create Resource Group'
description: 'Create Azure Resource Group'
inputs:
  rg-name:
    description: 'Name of Resource Group'
    required: true
  rg-location:
    description: 'Location of Resource Group'
    required: true
outputs:
  rg-name:
    description: "Name of Resource Group created"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  rg-provisioning-state:
    description: "Name of Resource Group created"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Generate Resource Group name
      id: rg-group-name
      run: |
        rgNAME="rg-${{ inputs.rg-name }}"
        echo "Creating Resource group naming convention"
        echo $rgNAME
        echo "rgName=$(echo $rgNAME)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create Resource Group
      run: |
        RG_NAME="${{ steps.rg-group-name.outputs.rgName }}"
        echo "Resource Group Name is $RG_NAME"
        
        if [ $(az group exists --name $RG_NAME) = false ]; then
          az group create --name $RG_NAME --location ${{ inputs.rg-location }}
        else
            echo "Resource group already exists"
        fi
      shell: bash
    
    - name: Show information
      run: |
        RG_NAME="${{ steps.rg-group-name.outputs.rgName }}"

        name_rg=$(az group show --name $RG_NAME --output tsv --query name)
        echo "Resource Group Name is $name_rg"
        
        state_rg=$(az group show --name $RG_NAME --output tsv --query properties.provisioningState)
        echo "Provisioning State is $state_rg"

        echo "rg_name=$name_rg" >> $GITHUB_OUTPUT
        echo "rg_provisioning-state=$state_rg" >> $GITHUB_OUTPUT
      shell: bash