name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Hello
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    
    - name: Create random number
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: GitHub Action Path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    
    - name: Make goodbye.sh executable
      run: chmod +x goodbye.sh
      shell: bash
  
    - name: Call goodbye.sh script
      run: goodbye.sh
      shell: bash
